apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-flower-be
  namespace: buy-flower-staging
  labels:
    app: buy-flower-be
    tier: api
spec:
  replicas: 1
  template:
    metadata:
      name: buy-flower-be
      labels:
        app: buy-flower-be
        tier: api
    spec:
      containers:
        - name: buy-flower-be
          image: ghcr.io/whoant221/buy-flower-be:VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
                { name: secret.buy-flower }
            - configMapRef:
                { name: configmap.buy-flower }
      restartPolicy: Always
  selector:
    matchLabels:
      app: buy-flower-be
      tier: api
