apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
  namespace: buy-flower-staging
  labels:
    app: sidekiq
    tier: job
spec:
  replicas: 1
  template:
    metadata:
      name: sidekiq
      labels:
        app: sidekiq
        tier: job
    spec:
      containers:
        - name: sidekiq
          image: ghcr.io/whoant221/buy-flower-be:VERSION
          imagePullPolicy: IfNotPresent
          command:
            - "/opt/buy-flower/docker/sidekiq.sh"
          envFrom:
            - secretRef:
                { name: secret.buy-flower }
            - configMapRef:
                { name: configmap.buy-flower }
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "100Mi"
              cpu: "100m"
      restartPolicy: Always
  selector:
    matchLabels:
      app: sidekiq
      tier: job
