apiVersion: apps/v1
kind: Deployment
metadata:
  name: buy-flower-be-deployment
  namespace: buy-flower
  labels:
    app: buy-flower-be
spec:
  replicas: 1
  template:
    metadata:
      name: buy-flower-be-deployment
      labels:
        app: buy-flower-be
    spec:
      containers:
        - name: buy-flower-be
          image: ghcr.io/whoant221/buy-flower-be:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          envFrom:
            - secretRef:
                { name: secret.buy-flower }
            - configMapRef:
                { name: configmap.buy-flower }
      
      restartPolicy: Always
  selector:
    matchLabels:
      app: buy-flower-be
